# -*- coding: utf-8 -*-
"""
Created on Fri May 27 17:23:42 2022

@author: hbckleikamp
"""
#custom reformatting script

import pandas as pd
import numpy as np

files=    [] #input list of .mgf files here as generated by msconvert




for file in files:


    with open(file) as f:
        lines=f.readlines()
    

        lines=[l.splitlines()[0] for l in lines]
        lines=np.array(lines)
        lines=np.array(np.split(lines,np.argwhere(lines=="BEGIN IONS").flatten()[1:]))
        
        ls=[]
        for ix,l in enumerate(lines):
            l=list(l)
        
            s=l[3].split()
            l[3]=s[0]
            rt=l.pop(2)
            # l[3]+="+"
            
            if "scan" in l[1]:
                l.insert(4,"SCANS="+str(l[1].split("scan=")[1].split(".")[0]))
            else:
                l.insert(4,"SCANS="+str(ix))
                
                
            l.insert(5,rt)
            l.insert(6,"SEQ=") # #mock peptide sequence
            # l[0]+="S"
            # l[-1]+="S"
            l.append("")
            ls.extend(l)
            
        ls="\n".join(ls)+"\n"
        with open(file.replace(".mgf","_rf.mgf"), "w") as w:
            w.write(ls)
    
